In [77]:
import numpy as np

In [78]:
%pip install numpy pandas matplotlib seaborn scikit-learn tensorflow jupyter ipykernel

Requirement already satisfied: numpy in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (3.0.5)
Requirement already satisfied: matplotlib in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (1.9.0)
Requirement already satisfied: tensorflow in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (2.21.0)
Requirement already satisfied: jupyter in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (1.1.1)
Requirement already satisfied: ipykernel in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (7.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (7.36.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (83.0.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (1.83.0)
Requirement already satisfied: keras>=3.12.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: notebook in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter) (7.6.2)
Requirement already satisfied: jupyter-console in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter) (7.17.1)
Requirement already satisfied: ipywidgets in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter) (8.1.9)
Requirement already satisfied: jupyterlab in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter) (4.6.3)
Requirement already satisfied: comm>=0.1.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (9.16.1)
Requirement already satisfied: jupyter-client>=8.9.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (8.9.1)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (1.7.2)
Requirement already satisfied: psutil>=5.7 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (27.2.0)
Requirement already satisfied: tornado>=6.4.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (6.5.8)
Requirement already satisfied: traitlets>=5.4.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipykernel) (5.16.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.53)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipython>=7.23.1->ipykernel) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: platformdirs>=2.5 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.11.4)
Requirement already satisfied: rich in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: executing>=1.2.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.2)
Requirement already satisfied: pure_eval in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.16 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipywidgets->jupyter) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from ipywidgets->jupyter) (3.0.17)
Requirement already satisfied: async-lru>=1.0.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-builder>=1.0.2 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab->jupyter) (1.2.2)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab->jupyter) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab->jupyter) (2.20.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: anyio in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.14.2)
Requirement already satisfied: httpcore==1.* in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (5.11.1)
Requirement already satisfied: overrides>=5.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.26.0)
Requirement already satisfied: pywinpty!=3.0.4,>=2.0.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0.5)
Requirement already satisfied: send2trash>=1.8.2 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.9.0)
Requirement already satisfied: babel>=2.10 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: argon2-cffi-bindings in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2026.6.3)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (4.2.0)
Requirement already satisfied: pyyaml>=5.3 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from nbconvert->jupyter) (4.15.0)
Requirement already satisfied: bleach!=5.0.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.4.0)
Requirement already satisfied: defusedxml in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from nbconvert->jupyter) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from nbconvert->jupyter) (0.11.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\Users\Nitesh verma\anaconda3\envs\tensorflow\Lib\site-packages (from nbconvert->jupyter) (1.5.1)

In [79]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [80]:
df = pd.read_csv("plant_water_data_1000.csv")

In [81]:
df

     soil_moisture  temperature_c  sunlight_hours  needs_water
0             0.37             32               2            1
1             0.86             29               5            0
2             0.67             33               4            0
3             0.56             25              11            0
4             0.18             34               2            1
..             ...            ...             ...          ...
995           0.13             29               3            1
996           0.83             28               6            0
997           0.17             28              10            1
998           0.86             30              10            0
999           0.43             35               5            1

[1000 rows x 4 columns]

In [82]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [83]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df[['needs_water']]

In [84]:
X_min = X.min()
X_max = X.max()
X_scaled = (X -X_min)/(X_max - X_min +1e-8)

In [85]:
X_scaled

     soil_moisture  temperature_c  sunlight_hours
0         0.376471       0.823529        0.090909
1         0.952941       0.647059        0.363636
2         0.729412       0.882353        0.272727
3         0.600000       0.411765        0.909091
4         0.152941       0.941176        0.090909
..             ...            ...             ...
995       0.094118       0.647059        0.181818
996       0.917647       0.588235        0.454545
997       0.141176       0.588235        0.818182
998       0.952941       0.705882        0.818182
999       0.447059       1.000000        0.363636

[1000 rows x 3 columns]

In [86]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

In [87]:
model  = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [88]:
model.compile(optimizer='sgd',loss='binary_crossentropy', metrics=['accuracy'])

In [89]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = [X_test.values,y_test.values],
    epochs = 100,batch_size = 4, verbose = 1
)

Epoch 1/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5107 - loss: 0.8981 - val_accuracy: 0.4160 - val_loss: 0.7114
Epoch 2/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5427 - loss: 0.6991 - val_accuracy: 0.5880 - val_loss: 0.8157
Epoch 3/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5987 - loss: 0.6755 - val_accuracy: 0.5880 - val_loss: 0.6929
Epoch 4/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6173 - loss: 0.6660 - val_accuracy: 0.6000 - val_loss: 0.6530
Epoch 5/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6000 - loss: 0.6662 - val_accuracy: 0.5880 - val_loss: 0.6505
Epoch 6/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5973 - loss: 0.6638 - val_accuracy: 0.5880 - val_loss: 0.6486
Epoch 7/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6253 - loss: 0.6537 - val_accuracy: 0.7800 - val_loss: 0.6310
Epoch 8/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6387 - loss: 0.6393 - val_accuracy: 0.5880 - val_loss: 0.6526
Epoch 9/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6107 - loss: 0.6586 - val_accuracy: 0.5960 - val_loss: 0.6207
Epoch 10/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6307 - loss: 0.6475 - val_accuracy: 0.5200 - val_loss: 0.6629
Epoch 11/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6253 - loss: 0.6446 - val_accuracy: 0.8360 - val_loss: 0.5981
Epoch 12/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6453 - loss: 0.6379 - val_accuracy: 0.7680 - val_loss: 0.6070
Epoch 13/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6547 - loss: 0.6343 - val_accuracy: 0.4840 - val_loss: 0.7267
Epoch 14/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6440 - loss: 0.6289 - val_accuracy: 0.5880 - val_loss: 0.6981
Epoch 15/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.6325 - val_accuracy: 0.6680 - val_loss: 0.5799
Epoch 16/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6653 - loss: 0.6118 - val_accuracy: 0.5280 - val_loss: 0.6662
Epoch 17/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6427 - loss: 0.6261 - val_accuracy: 0.8440 - val_loss: 0.5548
Epoch 18/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6480 - loss: 0.6190 - val_accuracy: 0.8280 - val_loss: 0.5357
Epoch 19/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6733 - loss: 0.5993 - val_accuracy: 0.5880 - val_loss: 0.7667
Epoch 20/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6520 - loss: 0.6093 - val_accuracy: 0.8600 - val_loss: 0.5330
Epoch 21/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6007 - val_accuracy: 0.5880 - val_loss: 0.6326
Epoch 22/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7093 - loss: 0.5788 - val_accuracy: 0.8800 - val_loss: 0.5020
Epoch 23/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7040 - loss: 0.5761 - val_accuracy: 0.4400 - val_loss: 0.8259
Epoch 24/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6960 - loss: 0.5865 - val_accuracy: 0.8800 - val_loss: 0.4893
Epoch 25/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6787 - loss: 0.5882 - val_accuracy: 0.5880 - val_loss: 0.7625
Epoch 26/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7027 - loss: 0.5652 - val_accuracy: 0.5880 - val_loss: 0.6836
Epoch 27/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7080 - loss: 0.5554 - val_accuracy: 0.4240 - val_loss: 0.9868
Epoch 28/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6947 - loss: 0.5750 - val_accuracy: 0.5880 - val_loss: 0.6160
Epoch 29/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6907 - loss: 0.5683 - val_accuracy: 0.4480 - val_loss: 0.7873
Epoch 30/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7133 - loss: 0.5476 - val_accuracy: 0.4280 - val_loss: 0.9462
Epoch 31/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7187 - loss: 0.5448 - val_accuracy: 0.4720 - val_loss: 0.8278
Epoch 32/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7320 - loss: 0.5239 - val_accuracy: 0.4480 - val_loss: 0.9107
Epoch 33/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7147 - loss: 0.5386 - val_accuracy: 0.4400 - val_loss: 0.8581
Epoch 34/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7387 - loss: 0.5260 - val_accuracy: 0.4200 - val_loss: 1.2583
Epoch 35/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7347 - loss: 0.5379 - val_accuracy: 0.9000 - val_loss: 0.4063
Epoch 36/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7200 - loss: 0.5227 - val_accuracy: 0.5040 - val_loss: 0.7642
Epoch 37/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7240 - loss: 0.5219 - val_accuracy: 0.6560 - val_loss: 0.4959
Epoch 38/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7253 - loss: 0.5140 - val_accuracy: 0.9240 - val_loss: 0.3811
Epoch 39/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7467 - loss: 0.5073 - val_accuracy: 0.6880 - val_loss: 0.4675
Epoch 40/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7507 - loss: 0.5165 - val_accuracy: 0.8320 - val_loss: 0.3733
Epoch 41/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7600 - loss: 0.4929 - val_accuracy: 0.6880 - val_loss: 0.5140
Epoch 42/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7520 - loss: 0.5374 - val_accuracy: 0.6360 - val_loss: 0.5051
Epoch 43/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7533 - loss: 0.4967 - val_accuracy: 0.6040 - val_loss: 0.5466
Epoch 44/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7547 - loss: 0.4772 - val_accuracy: 0.4600 - val_loss: 1.0024
Epoch 45/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7600 - loss: 0.4959 - val_accuracy: 0.4160 - val_loss: 1.8732
Epoch 46/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7840 - loss: 0.4831 - val_accuracy: 0.9000 - val_loss: 0.3668
Epoch 47/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7547 - loss: 0.4890 - val_accuracy: 0.5880 - val_loss: 0.7899
Epoch 48/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7840 - loss: 0.4626 - val_accuracy: 0.9240 - val_loss: 0.3110
Epoch 49/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7813 - loss: 0.4618 - val_accuracy: 0.5000 - val_loss: 0.9007
Epoch 50/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7707 - loss: 0.4649 - val_accuracy: 0.4200 - val_loss: 1.8215
Epoch 51/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8067 - loss: 0.4197 - val_accuracy: 0.9040 - val_loss: 0.2943
Epoch 52/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7800 - loss: 0.4606 - val_accuracy: 0.9160 - val_loss: 0.3050
Epoch 53/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7787 - loss: 0.4454 - val_accuracy: 0.7360 - val_loss: 0.4469
Epoch 54/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7907 - loss: 0.4456 - val_accuracy: 0.5120 - val_loss: 0.8752
Epoch 55/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7653 - loss: 0.4692 - val_accuracy: 0.6200 - val_loss: 0.5983
Epoch 56/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8067 - loss: 0.4179 - val_accuracy: 0.8440 - val_loss: 0.3209
Epoch 57/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8000 - loss: 0.4213 - val_accuracy: 0.9400 - val_loss: 0.2757
Epoch 58/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7973 - loss: 0.4169 - val_accuracy: 0.9600 - val_loss: 0.2664
Epoch 59/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8133 - loss: 0.4040 - val_accuracy: 0.9600 - val_loss: 0.2412
Epoch 60/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7813 - loss: 0.4868 - val_accuracy: 0.8800 - val_loss: 0.3124
Epoch 61/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8013 - loss: 0.4269 - val_accuracy: 0.9720 - val_loss: 0.2414
Epoch 62/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7987 - loss: 0.4253 - val_accuracy: 0.7160 - val_loss: 0.5118
Epoch 63/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8173 - loss: 0.4105 - val_accuracy: 0.9600 - val_loss: 0.2311
Epoch 64/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8040 - loss: 0.4216 - val_accuracy: 0.5120 - val_loss: 1.0024
Epoch 65/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8387 - loss: 0.3534 - val_accuracy: 0.5360 - val_loss: 0.8458
Epoch 66/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8067 - loss: 0.4119 - val_accuracy: 0.6720 - val_loss: 0.5851
Epoch 67/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8160 - loss: 0.4024 - val_accuracy: 0.8320 - val_loss: 0.3994
Epoch 68/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8147 - loss: 0.3963 - val_accuracy: 0.7800 - val_loss: 0.3661
Epoch 69/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8267 - loss: 0.3808 - val_accuracy: 0.8600 - val_loss: 0.2919
Epoch 70/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8440 - loss: 0.3730 - val_accuracy: 0.6840 - val_loss: 0.5634
Epoch 71/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8293 - loss: 0.3713 - val_accuracy: 0.7240 - val_loss: 0.5206
Epoch 72/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.3580 - val_accuracy: 0.4560 - val_loss: 1.6152
Epoch 73/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8240 - loss: 0.3930 - val_accuracy: 0.9560 - val_loss: 0.2244
Epoch 74/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8267 - loss: 0.3835 - val_accuracy: 0.9040 - val_loss: 0.2301
Epoch 75/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8320 - loss: 0.3756 - val_accuracy: 0.6080 - val_loss: 0.8406
Epoch 76/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8160 - loss: 0.4023 - val_accuracy: 0.9720 - val_loss: 0.1981
Epoch 77/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3321 - val_accuracy: 0.7040 - val_loss: 0.5826
Epoch 78/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8213 - loss: 0.3745 - val_accuracy: 0.5880 - val_loss: 1.1940
Epoch 79/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8520 - loss: 0.3566 - val_accuracy: 0.9680 - val_loss: 0.1905
Epoch 80/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8280 - loss: 0.4072 - val_accuracy: 0.9480 - val_loss: 0.2151
Epoch 81/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8427 - loss: 0.3558 - val_accuracy: 0.7520 - val_loss: 0.4695
Epoch 82/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8453 - loss: 0.3435 - val_accuracy: 0.9440 - val_loss: 0.1976
Epoch 83/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8493 - loss: 0.3215 - val_accuracy: 0.9680 - val_loss: 0.1768
Epoch 84/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8427 - loss: 0.3453 - val_accuracy: 0.9360 - val_loss: 0.2001
Epoch 85/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8520 - loss: 0.3327 - val_accuracy: 0.9720 - val_loss: 0.1739
Epoch 86/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8747 - loss: 0.3372 - val_accuracy: 0.9040 - val_loss: 0.2030
Epoch 87/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8120 - loss: 0.4038 - val_accuracy: 0.9600 - val_loss: 0.1838
Epoch 88/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8667 - loss: 0.3228 - val_accuracy: 0.9320 - val_loss: 0.1928
Epoch 89/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8400 - loss: 0.3495 - val_accuracy: 0.7280 - val_loss: 0.5429
Epoch 90/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8520 - loss: 0.3305 - val_accuracy: 0.9720 - val_loss: 0.1748
Epoch 91/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8240 - loss: 0.3601 - val_accuracy: 0.9520 - val_loss: 0.1820
Epoch 92/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8560 - loss: 0.3394 - val_accuracy: 0.8680 - val_loss: 0.2714
Epoch 93/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8680 - loss: 0.3006 - val_accuracy: 0.4240 - val_loss: 2.5359
Epoch 94/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8493 - loss: 0.3835 - val_accuracy: 0.9120 - val_loss: 0.1999
Epoch 95/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8307 - loss: 0.3556 - val_accuracy: 0.8360 - val_loss: 0.3164
Epoch 96/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8600 - loss: 0.3176 - val_accuracy: 0.8600 - val_loss: 0.2844
Epoch 97/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8547 - loss: 0.3188 - val_accuracy: 0.9040 - val_loss: 0.2060
Epoch 98/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8680 - loss: 0.2873 - val_accuracy: 0.9360 - val_loss: 0.1776
Epoch 99/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8600 - loss: 0.3070 - val_accuracy: 0.9440 - val_loss: 0.1738
Epoch 100/100
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8467 - loss: 0.3483 - val_accuracy: 0.9640 - val_loss: 0.1631